#!/usr/bin/env sh

localdomain="wp-base.local"
adminpath="/wp-admin"

chromium --args --allow-insecure-localhost --host-resolver-rules="MAP $localdomain localhost" "https://$localdomain" "https://$localdomain$adminpath"

